global using System;
global using System.IO;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Collections.Generic;
global using System.Collections.Immutable;
global using System.Collections.Frozen;
global using System.Linq;
global using System.Linq.Expressions;
global using Eto.Forms;
global using static DistantWorlds.IDE.Helpers;