namespace DW2IDE;

// DPI_AWARENESS_CONTEXT
internal enum DpiAwarenessContext : int {

  //DPI_AWARENESS_CONTEXT_UNAWARE
  Unaware = 16,

  //DPI_AWARENESS_CONTEXT_SYSTEM_AWARE
  SystemAware = 17,

  //DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE
  PerMonitorAware = 18,

  //DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2
  PerMonitorAwareV2 = 34

}